[phases.setup]
nixPkgs = ["python39", "gcc"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "python -m nltk.downloader -d /tmp/nltk_data vader_lexicon punkt stopwords wordnet"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
